### ISSUE TITLE
7x8 level not working

### ISSUE THREAD

**Issue by trainzug** [dbellavista/rullo-solver#1]
First of all nice program! :)
But somehow it cant solve this level.

![index](https://user-images.githubusercontent.com/20605068/36441405-d5125974-1672-11e8-9c08-70e4cc29474d.jpeg)

3 2 2 4 4 4 2
3 2 4 3 4 4 3
3 4 3 3 4 2 3
2 2 4 2 3 3 3
4 4 2 2 4 4 2
3 3 3 3 3 4 2
3 3 4 2 4 2 4
2 3 2 4 2 3 4
16 12 16 19 24 19 13
19 13 15 16 14 14 18 10

**Comment by dbellavista** [comment]
O.o I made the assumption of only NxN levels.
Thanks for reporting!
